// Package organizations is the identity Module's organization command layer.
// CreateOrganization is the first trusted command behind the Bearer JWT
// transport: the client generates the organization id as the idempotency key,
// and one transaction as identity_app writes the organization row together
// with the creator's first Owner membership.
package organizations

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"regexp"
	"strings"

	"github.com/jackc/pgx/v5"

	"github.com/nevix-ai/server/internal/identity/authjwt"
	"github.com/nevix-ai/server/internal/identity/command"
	"github.com/nevix-ai/server/internal/identity/writetx"
)

var (
	// errIDConflict means the client-generated id already belongs to an
	// organization whose active Owner is someone else: a retry must never
	// silently return another user's organization.
	errIDConflict            = errors.New("organizations: id belongs to another user's organization")
	errInvalidOrganizationID = errors.New("organizations: invalid organization id")
	errOrganizationNotFound  = errors.New("organizations: organization not found")
	errInsufficientRole      = errors.New("organizations: insufficient organization role")
)

// uuidPattern accepts the canonical lowercase-or-uppercase UUID text form the
// client generates; the database column stays the source of truth.
var uuidPattern = regexp.MustCompile(`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$`)

// Manager handles Organization trusted commands through the identity_app
// write-transaction runner.
type Manager struct {
	tx *writetx.Runner
}

func NewManager(tx *writetx.Runner) *Manager {
	return &Manager{tx: tx}
}

// CreateOrganizationRequest is the CreateOrganization command input. Validate
// preserves the existing distinction between omitted fields, an invalid UUID,
// and a name that becomes blank after normalization.
type CreateOrganizationRequest struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// Validate normalizes command input before returning the established request
// error. Capturing field presence first preserves the prior omitted-field
// behavior while keeping whitespace-only names distinct.
func (r *CreateOrganizationRequest) Validate() *command.Error {
	missingID, missingName := r.ID == "", r.Name == ""
	r.ID = strings.ToLower(strings.TrimSpace(r.ID))
	r.Name = strings.TrimSpace(r.Name)
	if missingID || missingName {
		return &command.Error{Status: http.StatusBadRequest, Code: "invalid_request", Message: "Request body must be JSON with id and name fields."}
	}
	if !uuidPattern.MatchString(r.ID) {
		return &command.Error{Status: http.StatusBadRequest, Code: "invalid_organization_id", Message: "id must be a UUID generated by the client."}
	}
	if r.Name == "" {
		return &command.Error{Status: http.StatusBadRequest, Code: "invalid_organization_name", Message: "name must not be blank."}
	}
	return nil
}

// OrganizationResponse is the minimal representation returned after an
// Organization command.
type OrganizationResponse struct {
	Organization struct {
		ID   string `json:"id"`
		Name string `json:"name"`
	} `json:"organization"`
}

// CreateOrganizationResponse is retained as the explicit Create command
// response name while sharing the Organization response representation.
type CreateOrganizationResponse = OrganizationResponse

// CreateOrganization runs the trusted command after the shared skeleton has
// decoded and validated its request. The Bearer guard supplies the user id in
// ctx before this function runs.
func (m *Manager) CreateOrganization(ctx context.Context, req CreateOrganizationRequest) (CreateOrganizationResponse, error) {
	storedName, err := m.create(ctx, authjwt.UserID(ctx), req.ID, req.Name)
	if err != nil {
		return CreateOrganizationResponse{}, err
	}
	var response CreateOrganizationResponse
	response.Organization.ID = req.ID
	response.Organization.Name = storedName
	return response, nil
}

// MapError translates organization-domain errors to the trusted-command
// contract. Unrecognized failures are logged and mapped to 500 by command.
func MapError(err error) *command.Error {
	switch {
	case errors.Is(err, errIDConflict):
		return &command.Error{Status: http.StatusConflict, Code: "organization_id_conflict", Message: "This organization id is already in use."}
	case errors.Is(err, errInvalidOrganizationID):
		return &command.Error{Status: http.StatusBadRequest, Code: "invalid_organization_id", Message: "organization_id must be a UUID."}
	case errors.Is(err, errOrganizationNotFound):
		return &command.Error{Status: http.StatusNotFound, Code: "organization_not_found", Message: "The organization was not found."}
	case errors.Is(err, errInsufficientRole):
		return &command.Error{Status: http.StatusForbidden, Code: "insufficient_organization_role", Message: "Owner role is required."}
	default:
		return nil
	}
}

// create runs the command transaction through the write runner. The
// client-generated id is the idempotency key: an insert conflict for the same
// active Owner is a no-op that returns the existing organization, while a
// conflict owned by anyone else is rejected. The FOR UPDATE read on the
// conflict path waits out a concurrent winner, so a retry never observes a
// half-created organization.
func (m *Manager) create(ctx context.Context, userID, id, name string) (string, error) {
	var storedName string
	err := m.tx.Run(ctx, func(tx pgx.Tx) error {
		var insertedID string
		err := tx.QueryRow(ctx,
			`INSERT INTO public.organizations (id, name) VALUES ($1, $2)
			 ON CONFLICT (id) DO NOTHING
			 RETURNING id`, id, name,
		).Scan(&insertedID)
		conflict := errors.Is(err, pgx.ErrNoRows)
		if err != nil && !conflict {
			return fmt.Errorf("organizations: insert organization: %w", err)
		}

		if conflict {
			if err := tx.QueryRow(ctx,
				`SELECT name FROM public.organizations WHERE id = $1 FOR UPDATE`, id,
			).Scan(&storedName); err != nil {
				return fmt.Errorf("organizations: read conflicting organization: %w", err)
			}
			var isOwner bool
			if err := tx.QueryRow(ctx,
				`SELECT EXISTS (
				     SELECT 1 FROM public.memberships
				     WHERE organization_id = $1 AND user_id = $2
				       AND status = 'active' AND role = 'owner')`, id, userID,
			).Scan(&isOwner); err != nil {
				return fmt.Errorf("organizations: check conflicting owner: %w", err)
			}
			if !isOwner {
				return errIDConflict
			}
			return nil
		}

		// The organization row and its first Owner membership commit atomically:
		// the active-owner unique index backs the transaction if two creators
		// raced on the same id.
		if _, err := tx.Exec(ctx,
			`INSERT INTO public.memberships (organization_id, user_id, role, status)
			 VALUES ($1, $2, 'owner', 'active')`, id, userID,
		); err != nil {
			return fmt.Errorf("organizations: insert owner membership: %w", err)
		}
		storedName = name
		return nil
	})
	if err != nil {
		return "", err
	}
	return storedName, nil
}

func normalizeOrganizationID(raw string) (string, error) {
	organizationID := strings.ToLower(strings.TrimSpace(raw))
	if !uuidPattern.MatchString(organizationID) {
		return "", errInvalidOrganizationID
	}
	return organizationID, nil
}
