// Package organizations is the identity Module's organization command layer.
// CreateOrganization is the first trusted command behind the Bearer JWT
// transport: the client generates the organization id as the idempotency key,
// and one transaction as identity_app writes the organization row together
// with the creator's first Owner membership.
package organizations

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"regexp"
	"strings"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/nevix-ai/server/internal/identity/authjwt"
	"github.com/nevix-ai/server/internal/identity/command"
)

// errIDConflict means the client-generated id already belongs to an
// organization whose active Owner is someone else: a retry must never
// silently return another user's organization.
var errIDConflict = errors.New("organizations: id belongs to another user's organization")

// uuidPattern accepts the canonical lowercase-or-uppercase UUID text form the
// client generates; the database column stays the source of truth.
var uuidPattern = regexp.MustCompile(`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$`)

// Creator handles the CreateOrganization command.
type Creator struct {
	pool *pgxpool.Pool
}

func NewCreator(pool *pgxpool.Pool) *Creator {
	return &Creator{pool: pool}
}

// CreateOrganizationRequest is the CreateOrganization command input. Validate
// preserves the existing distinction between omitted fields, an invalid UUID,
// and a name that becomes blank after normalization.
type CreateOrganizationRequest struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// Validate normalizes command input before returning the established request
// error. Capturing field presence first preserves the prior omitted-field
// behavior while keeping whitespace-only names distinct.
func (r *CreateOrganizationRequest) Validate() *command.Error {
	missingID, missingName := r.ID == "", r.Name == ""
	r.ID = strings.ToLower(strings.TrimSpace(r.ID))
	r.Name = strings.TrimSpace(r.Name)
	if missingID || missingName {
		return &command.Error{Status: http.StatusBadRequest, Code: "invalid_request", Message: "Request body must be JSON with id and name fields."}
	}
	if !uuidPattern.MatchString(r.ID) {
		return &command.Error{Status: http.StatusBadRequest, Code: "invalid_organization_id", Message: "id must be a UUID generated by the client."}
	}
	if r.Name == "" {
		return &command.Error{Status: http.StatusBadRequest, Code: "invalid_organization_name", Message: "name must not be blank."}
	}
	return nil
}

// CreateOrganizationResponse is the minimal representation returned after a
// successful create or same-user idempotent retry.
type CreateOrganizationResponse struct {
	Organization struct {
		ID   string `json:"id"`
		Name string `json:"name"`
	} `json:"organization"`
}

// CreateOrganization runs the trusted command after the shared skeleton has
// decoded and validated its request. The Bearer guard supplies the user id in
// ctx before this function runs.
func (c *Creator) CreateOrganization(ctx context.Context, req CreateOrganizationRequest) (CreateOrganizationResponse, error) {
	storedName, err := c.create(ctx, authjwt.UserID(ctx), req.ID, req.Name)
	if err != nil {
		return CreateOrganizationResponse{}, err
	}
	var response CreateOrganizationResponse
	response.Organization.ID = req.ID
	response.Organization.Name = storedName
	return response, nil
}

// MapError translates organization-domain errors to the trusted-command
// contract. Unrecognized failures are logged and mapped to 500 by command.
func MapError(err error) *command.Error {
	if errors.Is(err, errIDConflict) {
		return &command.Error{Status: http.StatusConflict, Code: "organization_id_conflict", Message: "This organization id is already in use."}
	}
	return nil
}

// create runs the command transaction as identity_app. The client-generated
// id is the idempotency key: an insert conflict for the same active Owner is
// a no-op that returns the existing organization, while a conflict owned by
// anyone else is rejected. The FOR UPDATE read on the conflict path waits out
// a concurrent winner, so a retry never observes a half-created organization.
func (c *Creator) create(ctx context.Context, userID, id, name string) (string, error) {
	tx, err := c.pool.Begin(ctx)
	if err != nil {
		return "", fmt.Errorf("organizations: begin create: %w", err)
	}
	defer tx.Rollback(context.WithoutCancel(ctx))

	if _, err := tx.Exec(ctx, "SET LOCAL ROLE identity_app"); err != nil {
		return "", fmt.Errorf("organizations: switch to identity_app: %w", err)
	}

	var insertedID string
	err = tx.QueryRow(ctx,
		`INSERT INTO public.organizations (id, name) VALUES ($1, $2)
		 ON CONFLICT (id) DO NOTHING
		 RETURNING id`, id, name,
	).Scan(&insertedID)
	conflict := errors.Is(err, pgx.ErrNoRows)
	if err != nil && !conflict {
		return "", fmt.Errorf("organizations: insert organization: %w", err)
	}

	if conflict {
		var storedName string
		if err := tx.QueryRow(ctx,
			`SELECT name FROM public.organizations WHERE id = $1 FOR UPDATE`, id,
		).Scan(&storedName); err != nil {
			return "", fmt.Errorf("organizations: read conflicting organization: %w", err)
		}
		var isOwner bool
		if err := tx.QueryRow(ctx,
			`SELECT EXISTS (
			     SELECT 1 FROM public.memberships
			     WHERE organization_id = $1 AND user_id = $2
			       AND status = 'active' AND role = 'owner')`, id, userID,
		).Scan(&isOwner); err != nil {
			return "", fmt.Errorf("organizations: check conflicting owner: %w", err)
		}
		if !isOwner {
			return "", errIDConflict
		}
		if err := tx.Commit(context.WithoutCancel(ctx)); err != nil {
			return "", fmt.Errorf("organizations: commit idempotent create: %w", err)
		}
		return storedName, nil
	}

	// The organization row and its first Owner membership commit atomically:
	// the active-owner unique index backs the transaction if two creators
	// raced on the same id.
	if _, err := tx.Exec(ctx,
		`INSERT INTO public.memberships (organization_id, user_id, role, status)
		 VALUES ($1, $2, 'owner', 'active')`, id, userID,
	); err != nil {
		return "", fmt.Errorf("organizations: insert owner membership: %w", err)
	}
	if err := tx.Commit(context.WithoutCancel(ctx)); err != nil {
		return "", fmt.Errorf("organizations: commit create: %w", err)
	}
	return name, nil
}
