// Package organizations is the identity Module's organization command layer.
// CreateOrganization is the first trusted command behind the Bearer JWT
// transport: the client generates the organization id as the idempotency key,
// and one transaction as identity_app writes the organization row together
// with the creator's first Owner membership.
package organizations

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"regexp"
	"strings"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/nevix-ai/server/internal/identity/authjwt"
)

// errIDConflict means the client-generated id already belongs to an
// organization whose active Owner is someone else: a retry must never
// silently return another user's organization.
var errIDConflict = errors.New("organizations: id belongs to another user's organization")

// uuidPattern accepts the canonical lowercase-or-uppercase UUID text form the
// client generates; the database column stays the source of truth.
var uuidPattern = regexp.MustCompile(`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$`)

// Creator handles the CreateOrganization command.
type Creator struct {
	pool *pgxpool.Pool
}

func NewCreator(pool *pgxpool.Pool) *Creator {
	return &Creator{pool: pool}
}

type createOrganizationRequest struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// ServeHTTP is the external CreateOrganization command: 200 with the created
// (or, on a same-user retry, the existing) organization's minimal
// representation; the standard error envelope otherwise.
func (c *Creator) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	var req createOrganizationRequest
	if err := json.NewDecoder(http.MaxBytesReader(w, r.Body, 4096)).Decode(&req); err != nil || req.ID == "" || req.Name == "" {
		writeCreateError(w, http.StatusBadRequest, "invalid_request", "Request body must be JSON with id and name fields.")
		return
	}
	id := strings.ToLower(strings.TrimSpace(req.ID))
	if !uuidPattern.MatchString(id) {
		writeCreateError(w, http.StatusBadRequest, "invalid_organization_id", "id must be a UUID generated by the client.")
		return
	}
	name := strings.TrimSpace(req.Name)
	if name == "" {
		writeCreateError(w, http.StatusBadRequest, "invalid_organization_name", "name must not be blank.")
		return
	}

	storedName, err := c.create(r.Context(), authjwt.UserID(r.Context()), id, name)
	switch {
	case errors.Is(err, errIDConflict):
		writeCreateError(w, http.StatusConflict, "organization_id_conflict", "This organization id is already in use.")
	case err != nil:
		slog.Error("identity: create organization", "organization_id", id, "error", err)
		writeCreateError(w, http.StatusInternalServerError, "internal_error", "The organization could not be created.")
	default:
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_ = json.NewEncoder(w).Encode(map[string]any{
			"organization": map[string]string{"id": id, "name": storedName},
		})
	}
}

// create runs the command transaction as identity_app. The client-generated
// id is the idempotency key: an insert conflict for the same active Owner is
// a no-op that returns the existing organization, while a conflict owned by
// anyone else is rejected. The FOR UPDATE read on the conflict path waits out
// a concurrent winner, so a retry never observes a half-created organization.
func (c *Creator) create(ctx context.Context, userID, id, name string) (string, error) {
	tx, err := c.pool.Begin(ctx)
	if err != nil {
		return "", fmt.Errorf("organizations: begin create: %w", err)
	}
	defer tx.Rollback(context.WithoutCancel(ctx))

	if _, err := tx.Exec(ctx, "SET LOCAL ROLE identity_app"); err != nil {
		return "", fmt.Errorf("organizations: switch to identity_app: %w", err)
	}

	var insertedID string
	err = tx.QueryRow(ctx,
		`INSERT INTO public.organizations (id, name) VALUES ($1, $2)
		 ON CONFLICT (id) DO NOTHING
		 RETURNING id`, id, name,
	).Scan(&insertedID)
	conflict := errors.Is(err, pgx.ErrNoRows)
	if err != nil && !conflict {
		return "", fmt.Errorf("organizations: insert organization: %w", err)
	}

	if conflict {
		var storedName string
		if err := tx.QueryRow(ctx,
			`SELECT name FROM public.organizations WHERE id = $1 FOR UPDATE`, id,
		).Scan(&storedName); err != nil {
			return "", fmt.Errorf("organizations: read conflicting organization: %w", err)
		}
		var isOwner bool
		if err := tx.QueryRow(ctx,
			`SELECT EXISTS (
			     SELECT 1 FROM public.memberships
			     WHERE organization_id = $1 AND user_id = $2
			       AND status = 'active' AND role = 'owner')`, id, userID,
		).Scan(&isOwner); err != nil {
			return "", fmt.Errorf("organizations: check conflicting owner: %w", err)
		}
		if !isOwner {
			return "", errIDConflict
		}
		if err := tx.Commit(context.WithoutCancel(ctx)); err != nil {
			return "", fmt.Errorf("organizations: commit idempotent create: %w", err)
		}
		return storedName, nil
	}

	// The organization row and its first Owner membership commit atomically:
	// the active-owner unique index backs the transaction if two creators
	// raced on the same id.
	if _, err := tx.Exec(ctx,
		`INSERT INTO public.memberships (organization_id, user_id, role, status)
		 VALUES ($1, $2, 'owner', 'active')`, id, userID,
	); err != nil {
		return "", fmt.Errorf("organizations: insert owner membership: %w", err)
	}
	if err := tx.Commit(context.WithoutCancel(ctx)); err != nil {
		return "", fmt.Errorf("organizations: commit create: %w", err)
	}
	return name, nil
}

func writeCreateError(w http.ResponseWriter, status int, errCode, message string) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	fmt.Fprintf(w, `{"error":%q,"message":%q}`, errCode, message)
}
