// Unit tests for the CreateOrganization request hook. It is the explicit
// domain-to-command validation seam; database behavior stays in integration.
package organizations

import "testing"

func TestCreateOrganizationRequestRejectsInvalidInput(t *testing.T) {
	for _, tc := range []struct {
		name      string
		request   CreateOrganizationRequest
		wantCode  string
		wantError string
	}{
		{
			name:      "missing id",
			request:   CreateOrganizationRequest{Name: "Acme"},
			wantCode:  "invalid_request",
			wantError: "Request body must be JSON with id and name fields.",
		},
		{
			name:      "missing name",
			request:   CreateOrganizationRequest{ID: "11111111-2222-3333-4444-555555555555"},
			wantCode:  "invalid_request",
			wantError: "Request body must be JSON with id and name fields.",
		},
		{
			name:      "id not a UUID",
			request:   CreateOrganizationRequest{ID: "not-a-uuid", Name: "Acme"},
			wantCode:  "invalid_organization_id",
			wantError: "id must be a UUID generated by the client.",
		},
		{
			name:      "blank name",
			request:   CreateOrganizationRequest{ID: "11111111-2222-3333-4444-555555555555", Name: "   "},
			wantCode:  "invalid_organization_name",
			wantError: "name must not be blank.",
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			err := tc.request.Validate()
			if err == nil {
				t.Fatal("Validate returned nil")
			}
			if err.Code != tc.wantCode || err.Message != tc.wantError {
				t.Fatalf("Validate returned (%q, %q), want (%q, %q)", err.Code, err.Message, tc.wantCode, tc.wantError)
			}
		})
	}
}

func TestCreateOrganizationRequestNormalizesBeforeBusinessFunction(t *testing.T) {
	request := CreateOrganizationRequest{
		ID:   "AAAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEEEE",
		Name: "  Acme  ",
	}

	if err := request.Validate(); err != nil {
		t.Fatalf("Validate returned %v", err)
	}
	if request.ID != "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee" {
		t.Fatalf("normalized id %q, want lowercase UUID", request.ID)
	}
	if request.Name != "Acme" {
		t.Fatalf("normalized name %q, want trimmed name", request.Name)
	}
}
